### PR TITLE
FEATURE: BEND-32 Update photo by

### PR DESCRIPTION
**Pull request by davidcode10**

### CODE REVIEW

**Comment by davidcode10** [comment]
Hi Manu,

I've done everything (I think),
But I have some doubts, I didn't understand some things in the description: 

- The accountId needed to delete the data will be get from req.user since this endpoint will be used only by the user. IT’S REALLY IMPORTANT (security enhacement) 
- Include a TODO inside the action which says: “Connect to S3”

Can you please explain me this points?

**Comment by whitehatdevv** [comment]
> Hi @whitehatdevv,
> 
> I've done everything (I think), But I have some doubts, I didn't understand some things in the description:
> 
> The accountId needed to delete the data will be get from req.user since this endpoint will be used only by the user. IT’S REALLY IMPORTANT (security enhacement) Include a TODO inside the action which says: “Connect to S3”
> 
> Can you please explain me this points? Waiting for your feedback,
> 
> Thanks!

The first think means that you have done the code rightly. 
The second one is to add a comment on the code putting // TODO: Connect to S3

@PatyVilas please review the code.

**Comment by whitehatdevv** [comment]
@davidcode10 @PatyVilas please fix the conflcits

**Comment by davidcode10** [comment]
@whitehatdevv ready to merge

**Pull request merged**
